### PR TITLE
Elektrix - Added support for 1.12 beta

### PR DESCRIPTION
**Pull request by CosignCosine**
- Added two new radio stations
- Added one new expansion pack
- Added one new content creator pack

I've confirmed this as working on my save (no simulation errors with all new packs)

Thanks for @boformer for guiding me through how to update this mod and to Gèze for uploading an old version of Assembly-CSharp.dll for me to compare.

### CODE REVIEW

**Comment by pitusko1** [comment]
hello @CosignCosine .I can't compile it propely, can you please give me more info? or your discord name please?
Thanks

**Comment by CosignCosine** [comment]
you should not be trying to compile this as it is now outdated.

make sure you can compile unsafe code.

**Comment by pitusko1** [comment]
I can compile unsafe code but I still cant run mod on 1.12 version. Now game doesn't even detect mod. in 1.11 it at least detected as outdated.

**Comment by CosignCosine** [comment]
> you should not be trying to compile this as it is now outdated.

**Comment by pitusko1** [comment]
i edited the code that you posted in Files changed. I try compiling after edit.

**Pull request closed without merging**
